language: csharp
mono: none
dotnet: 2.0.0
script:
  - dotnet restore
  - dotnet build ./GribTests/
  - dotnet test ./GribTests/
  - .nuget/packages/coveralls.net/0.7.0/tools/csmacnz.Coveralls.exe --opencover -i GribTests/coverage.xml  --useRelativePaths