configuration:
  - Debug
install:
    - nuget restore
    
before_build:
  - cmd: dotnet build GribViewer.sln

environment:
    COVERALLS_REPO_TOKEN:  
       secure: sbsbi0ah6fSXCGhUl+GWJlLcjfxudCTz3/UZdXVNW3daYx64UfqN2G9tel7Q4MVh
 
test_script:
  - cmd: cd GribTests
  - cmd: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
  - cmd: SET
  - cmd: IF "%CONFIGURATION%"=="Debug"  (%USERPROFILE%\.nuget\packages\coveralls.net\0.7.0\tools\csmacnz.Coveralls.exe --opencover -i coverage.xml --useRelativePaths --commitId %APPVEYOR_REPO_COMMIT% --jobId %APPVEYOR_JOB_ID%  --commitAuthor "%APPVEYOR_REPO_COMMIT_AUTHOR%" --commitEmail %APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL% --commitMessage "%APPVEYOR_REPO_COMMIT_MESSAGE%" --commitBranch %APPVEYOR_REPO_BRANCH% )